name=MAX7221UniDevice
version=1.0.6
author=Cyril BARBATO <cyril.barbato@gmx.com>
maintainer=Cyril BARBATO <cyril.barbato@gmx.com>
sentence=A C library from CPP orginal lib by Eberhard Fahle for the MAX7219 and the MAX7221 Led display drivers for 8051 and AVR architectures.
paragraph=The library supports multiple daisychained drivers and supports Led-Matrix displays as well as 7-Segment displays.
category=Display
url=https://sourceforge.net/projects/max7222-arduino
architectures=*
